2024-01-19 11:02:06,765 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2024-01-19 11:02:06,772 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\filip\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\instabot\bot\bot.py
2024-01-19 11:02:06,775 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2024-01-19 11:02:07,752 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2024-01-19 11:02:07,755 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2024-01-19 11:02:07,756 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2024-01-19 11:02:07,757 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
